### ISSUE TITLE
Fix the all screens in the game to be uniform on every devices

### ISSUE THREAD

**Issue by jafernoorani** [jafernoorani/UnhingedMonkey#3]
For issue #3, I would like to make a change that would allow the game screens to take full screen on each and every device that runs this program. As of now, when the game is launched by the user it does not take the full screen and has lots of white space if the device is bigger than a 11". I want to fix this issue so that way the user can take full advantage of all screen space given to them on their machine. When the user clicks through the different menus there are lots of issues with uniformity and this creates for a bad UX experience for the user. Going one step further I would like to create a scale so that way if the user increases/decreases the window size, everything will be scaled to fit on their screen.

In order to fix this I would have to change code within the MainApplication file. I would have to create some sort of scale for the whole window and would have to create new functions for this as the functionality for this does not exist yet. I would also like to create a minimum size and cut out all the whitespace that is visible when the application is full screened. Therefore this would have to be done within the GraphicsWindow and the MainApplication files. I would also have to do research on this in order to do this. I would start with those two files and would also create some more functions that would create a scale for my window, and I would also have to set some sort of minimum and maximum size for this. This would be a fun change to make and it would make our game a lot more playable and exciting.

**Comment by onzfonz** [comment]
I think just start with having a way to change the resolution based on a file or to put some aspect ratio in there and the when the program runs to use the info stored in that file.
Let me know if that doesn't make sense, but best of luck!
